# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Very Good Looking
email: info@verygoodlooking.info
description: > # this means to ignore newlines until "baseurl:"
  Experiments on the www by web designer Sandra Rosales
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site


permalink: /:categories/:title

links:
- title: about
  url: /about
- title: archive
  url: /archive

# Build settings
markdown: kramdown
